apiVersion: batch/v1
kind: CronJob
metadata:
  creationTimestamp: null
  name: every2min
spec:
  jobTemplate:
    metadata:
      creationTimestamp: null
      name: every2min
    spec:
      template:
        metadata:
          creationTimestamp: null
        spec:
          containers:
          - image: busybox
            name: every2min
            command: ["sleep"]
            args: ["300"]
            resources: {}
          restartPolicy: OnFailure
  schedule: '*/2 * * * *'
status: {}
